#!/usr/bin/env python3
"""
Build the screener history dataset used by the index page.

Input: daily_trust10_*.json reports generated by screener/daily_trust_monitor.py.
Output: public/data/screening_history.json and src/data/screening_history.json.
"""
from __future__ import annotations

import glob
import json
import os
from datetime import date, datetime
from pathlib import Path
from typing import Any

ARCHIVE_AFTER_DAYS = 30
PROJECT_ROOT = Path(__file__).resolve().parents[1]
PUBLIC_DATA_DIR = PROJECT_ROOT / "public" / "data"
SRC_DATA_DIR = PROJECT_ROOT / "src" / "data"
DEFAULT_REPORT_DIRS = (
    PROJECT_ROOT / "output" / "reports",
    PROJECT_ROOT / "screener" / "output" / "reports",
    Path("/root/tw-stock-monitor/output/reports"),
    Path.home() / "tw-stock-monitor" / "output" / "reports",
)
CRITERIA = (
    "投信十日買超金額排行前 100",
    "財報狗排除地雷股 80 分以上",
    "財報狗成長股 80 分以上",
    "樂活五線譜 3.5 年中線以下",
)


def parse_iso_date(value: str) -> date:
    return datetime.strptime(value, "%Y-%m-%d").date()


def classify_screening_status(last_screened_at: str, reference_date: str | None = None) -> dict[str, Any]:
    ref = parse_iso_date(reference_date) if reference_date else date.today()
    last_seen = parse_iso_date(last_screened_at)
    days_since_screened = max((ref - last_seen).days, 0)
    is_archive = days_since_screened >= ARCHIVE_AFTER_DAYS

    return {
        "screening_status": "archive" if is_archive else "active",
        "days_since_screened": days_since_screened,
        "archived_at": ref.isoformat() if is_archive else None,
    }


def find_reports_dir() -> Path | None:
    env_dir = os.environ.get("SCREENER_REPORTS_DIR")
    candidates = (Path(env_dir).expanduser(),) if env_dir else ()
    for reports_dir in (*candidates, *DEFAULT_REPORT_DIRS):
        if reports_dir.exists():
            return reports_dir
    return None


def report_paths(reports_dir: str | Path | None) -> list[Path]:
    if reports_dir is None:
        reports_dir = find_reports_dir()
    if reports_dir is None:
        return []

    reports_path = Path(reports_dir)
    patterns = [
        str(reports_path / "daily_trust10_*.json"),
        str(reports_path / "*" / "daily_trust10_*.json"),
    ]
    paths: list[Path] = []
    for pattern in patterns:
        paths.extend(Path(path) for path in glob.glob(pattern))
    return sorted(set(paths))


def normalize_report_record(raw: dict[str, Any], screened_at: str) -> dict[str, Any]:
    code = str(raw.get("code", "")).strip()
    name = str(raw.get("name_zh") or raw.get("name") or code).strip()
    price = raw.get("cur_price", raw.get("price"))

    return {
        "id": f"{screened_at}-{code}",
        "code": code,
        "name": name,
        "rank": raw.get("rank"),
        "price": price,
        "net_amount_10d": raw.get("net_amount_10d"),
        "net_amount_10d_k": raw.get("net_amount_10d_k"),
        "net_shares_10d": raw.get("net_shares_10d"),
        "net_shares_10d_zhang": raw.get("net_shares_10d_zhang"),
        "g_score": raw.get("g_score"),
        "l_score": raw.get("l_score"),
        "regression_z": raw.get("regression_z"),
        "last_buy_date": raw.get("last_date"),
        "statementdog_url": raw.get("statementdog_url"),
        "screened_at": screened_at,
    }


def load_report(path: Path) -> tuple[str, list[dict[str, Any]]]:
    with path.open(encoding="utf-8") as f:
        payload = json.load(f)

    screened_at = str(payload.get("date") or path.stem.replace("daily_trust10_", ""))
    if "-" not in screened_at and len(screened_at) == 8:
        screened_at = f"{screened_at[:4]}-{screened_at[4:6]}-{screened_at[6:8]}"

    rows = payload.get("top10") or payload.get("stocks") or payload.get("results") or []
    records = [
        normalize_report_record(row, screened_at)
        for row in rows
        if isinstance(row, dict) and str(row.get("code", "")).strip()
    ]
    return screened_at, records


def group_records_by_day(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    grouped: dict[str, list[dict[str, Any]]] = {}
    for record in records:
        grouped.setdefault(record["screened_at"], []).append(record)

    days = []
    for day in sorted(grouped.keys(), reverse=True):
        day_records = sorted(grouped[day], key=lambda item: item.get("rank") or 9999)
        days.append({"date": day, "count": len(day_records), "records": day_records})
    return days


def build_screening_history(reports_dir: str | Path | None = None, reference_date: str | None = None) -> dict[str, Any]:
    all_records: list[dict[str, Any]] = []
    trading_days: set[str] = set()

    for path in report_paths(reports_dir):
        screened_at, records = load_report(path)
        trading_days.add(screened_at)
        all_records.extend(records)

    last_seen_by_code: dict[str, str] = {}
    latest_record_by_code: dict[str, dict[str, Any]] = {}
    for record in sorted(all_records, key=lambda item: item["screened_at"]):
        code = record["code"]
        last_seen_by_code[code] = record["screened_at"]
        latest_record_by_code[code] = record

    active_records: list[dict[str, Any]] = []
    archive_records: list[dict[str, Any]] = []
    active_codes: set[str] = set()
    archive_codes: set[str] = set()

    for code, last_seen in last_seen_by_code.items():
        lifecycle = classify_screening_status(last_seen, reference_date)
        if lifecycle["screening_status"] == "archive":
            archive_codes.add(code)
            archive_records.append({**latest_record_by_code[code], **lifecycle})
        else:
            active_codes.add(code)

    for record in all_records:
        code = record["code"]
        if code in active_codes:
            lifecycle = classify_screening_status(last_seen_by_code[code], reference_date)
            active_records.append({**record, **lifecycle})

    active_days = group_records_by_day(active_records)
    archive_days = group_records_by_day(archive_records)

    return {
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "reference_date": reference_date or date.today().isoformat(),
        "criteria": list(CRITERIA),
        "summary": {
            "active_stocks": len(active_codes),
            "archive_stocks": len(archive_codes),
            "trading_days": len(trading_days),
            "total_records": len(all_records),
        },
        "active_days": active_days,
        "archive_days": archive_days,
    }


def write_screening_history(payload: dict[str, Any], public_data_dir: Path, src_data_dir: Path) -> None:
    public_data_dir.mkdir(parents=True, exist_ok=True)
    src_data_dir.mkdir(parents=True, exist_ok=True)
    for output_dir in (public_data_dir, src_data_dir):
        path = output_dir / "screening_history.json"
        with path.open("w", encoding="utf-8") as f:
            json.dump(payload, f, ensure_ascii=False, separators=(",", ":"))


def generate_screening_history(
    reports_dir: str | Path | None = None,
    public_data_dir: str | Path = PUBLIC_DATA_DIR,
    src_data_dir: str | Path = SRC_DATA_DIR,
    reference_date: str | None = None,
) -> dict[str, Any]:
    payload = build_screening_history(reports_dir=reports_dir, reference_date=reference_date)
    write_screening_history(payload, Path(public_data_dir), Path(src_data_dir))
    return payload


def main() -> None:
    payload = generate_screening_history()
    print(
        "Generated screening_history.json: "
        f"{payload['summary']['active_stocks']} active, "
        f"{payload['summary']['archive_stocks']} archive, "
        f"{payload['summary']['total_records']} records"
    )


if __name__ == "__main__":
    main()
