const test=require('node:test');const assert=require('node:assert/strict');let helpers={};try{helpers=require('./outcome.cjs');}catch(error){if(error.code!=='MODULE_NOT_FOUND')throw error;}
test('durable outcome distinguishes diagnostics and preserves independent statuses and exact counts',()=>{
 assert.equal(typeof helpers.operationOutcome,'function');
 const base={marketDate:'2026-10-02',requestId:'stockscreener:20261002:v1',actionsRunId:'123',notionPageId:'11111111-1111-1111-1111-111111111111',screeningStatus:'complete',notionStatus:'complete',deployStatus:'pending',expectedCount:0,archivedCount:0,stage:'done'};
 const out=helpers.operationOutcome({...base,errorCategory:'deploy_pending'});assert.equal(out.expectedCount,0);assert.equal(out.archivedCount,0);assert.equal(out.outcome,'deployment_pending');assert.equal(out.actionsUrl,'https://github.com/pingpongtech-uskg/stock-web-pages/actions/runs/123');
 assert.equal(helpers.operationOutcome({...base,screeningStatus:'diagnostic_verified',notionStatus:'credential_verified',deployStatus:'not_tested'}).outcome,'diagnostics_only');
 assert.equal(helpers.operationOutcome({...base,screeningStatus:'already_complete',deployStatus:'verified'}).outcome,'already_complete');
 assert.equal(helpers.operationOutcome({...base,screeningStatus:'failed',notionStatus:'failure_metadata',errorCategory:'screening_failed'}).outcome,'failed');
});
test('outcome never persists signed URL, payload, auth data or remote query strings',()=>{
 assert.equal(typeof helpers.operationOutcome,'function');
 const out=helpers.operationOutcome({stage:'done',marketDate:'2026-10-02',owner:'a',errorMessage:'failed https://host.example/file?signature=private',op:{url:'https://host.example/file?secret=private'},payload:{secret:'private'},publication:{publishedGitCommit:'a'.repeat(40),url:'https://secret'}});
 const raw=JSON.stringify(out);assert.equal(raw.includes('private'),false);assert.equal(raw.includes('https://secret'),false);assert.equal(Object.hasOwn(out,'payload'),false);assert.equal(Object.hasOwn(out,'op'),false);assert.equal(out.publishedGitCommit,'a'.repeat(40));
});
test('native dispatch 204/empty success and failed transport always continue exact-run recovery',()=>{
 assert.equal(typeof helpers.nativeDispatchResponse,'function');
 assert.equal(helpers.nativeDispatchResponse({}).statusCode,204);
 assert.equal(helpers.nativeDispatchResponse({error:{statusCode:403,message:'Forbidden'}}).statusCode,403);
 assert.equal(helpers.nativeDispatchResponse({error:{statusCode:403,message:'Forbidden'}}).error,undefined);
 assert.equal(helpers.nativeDispatchResponse({error:'ETIMEDOUT'}).statusCode,503);
 assert.equal(helpers.nativeDispatchResponse({error:{httpCode:'429'}}).statusCode,429);
 assert.equal(helpers.nativeDispatchResponse({error:{httpCode:'429',headers:{'retry-after':'10'}}}).headers['retry-after'],'10');
});
test('native local invalid JSON preserves a sanitized confirmed preflight failure',()=>{
 for(const error of ['Inputs: Invalid JSON',{message:'Inputs: Invalid JSON'}]) {
  const response=helpers.nativeDispatchResponse({error});
  assert.equal(response.statusCode,400);assert.equal(response.preflightFailed,true);
  assert.equal(response.body.message,'Inputs: Invalid JSON');assert.equal(response.error,undefined);
 }
 assert.equal(helpers.nativeDispatchResponse({error:'ETIMEDOUT'}).preflightFailed,undefined);
});
test('terminal primary failed outcome throws only sanitized category after pure observation remains available',()=>{const state={stage:'done',screeningStatus:'failed',notionStatus:'failure_metadata',errorCategory:'screening_failed',errorMessage:'https://private.invalid/?secret=hidden',payload:{private:'hidden'}};assert.equal(helpers.operationOutcome(state).outcome,'failed');assert.equal(typeof helpers.finalizeOperationOutcome,'function');assert.throws(()=>helpers.finalizeOperationOutcome(state),/^Error: Stockscreener operation failed: screening_failed$/);assert.throws(()=>helpers.finalizeOperationOutcome({...state,errorCategory:'https://private.invalid/?secret=hidden'}),/^Error: Stockscreener operation failed: operation_failed$/);assert.equal(state.errorCategory,'screening_failed');});
test('legitimate terminal primary results return without failure including recovery with retained old error',()=>{for(const state of [{stage:'done',released:true,cacheStatus:'pending_recovery',errorCategory:'old_failure'},{stage:'done',screeningStatus:'skipped_non_trading'},{stage:'done',screeningStatus:'already_complete'},{stage:'done',screeningStatus:'diagnostic_verified'},{stage:'done',screeningStatus:'complete',notionStatus:'complete',deployStatus:'verified'},{stage:'done',screeningStatus:'complete',notionStatus:'complete',deployStatus:'pending',errorCategory:'deploy_pending'}])assert.deepEqual(helpers.finalizeOperationOutcome(state),helpers.operationOutcome(state));});
test('ownership finalization marks failed acquisition native-failed without leaking provider details',()=>{assert.equal(typeof helpers.finalizeOwnershipOutcome,'function');for(const status of ['failed','acquisition_job_failed']){assert.throws(()=>helpers.finalizeOwnershipOutcome({status,errorCategory:'failure',errorMessage:'https://private/?secret=hidden',intent:{private:'hidden'}}),/^Error: Ownership acquisition failed: failure$/);assert.throws(()=>helpers.finalizeOwnershipOutcome({status,errorCategory:'private ? signed URL'}),/^Error: Ownership acquisition failed: acquisition_failed$/);}for(const status of ['acquisition_job_succeeded','skipped_non_trading','pending_recovery'])assert.equal(helpers.finalizeOwnershipOutcome({status,marketDate:'2026-10-05',requestId:'fixture'}).status,status);});

test('current cache failure overrides inherited completed publication while recovery and deployment pending stay legitimate',()=>{const base={stage:'done',screeningStatus:'complete',notionStatus:'complete',deployStatus:'verified',cacheStatus:'failed',errorCategory:'cache_download_failed'};assert.equal(helpers.operationOutcome(base).outcome,'failed');assert.throws(()=>helpers.finalizeOperationOutcome({...base,cacheStatus:'verified',errorCategory:'external_http_503'}),/^Error: Stockscreener operation failed: external_http_503$/);assert.throws(()=>helpers.finalizeOperationOutcome(base),/^Error: Stockscreener operation failed: cache_download_failed$/);assert.throws(()=>helpers.finalizeOperationOutcome({...base,cacheStatus:'pending_reconciliation',errorCategory:'cache_attachment_ambiguous'}),/^Error: Stockscreener operation failed: cache_attachment_ambiguous$/);assert.equal(helpers.finalizeOperationOutcome({...base,cacheStatus:'pending_recovery',released:true}).outcome,'pending_recovery');});

test('unowned terminal busy trigger and scheduled post-cutoff trigger are benign skips',()=>{for(const [state,expected] of [[{stage:'done',errorCategory:'writer_busy'},'skipped_writer_busy'],[{stage:'done',runKind:'scheduled',errorCategory:'operation_overdue'},'skipped_after_cutoff']]){const before={...state};assert.equal(helpers.operationOutcome(state).outcome,expected);assert.equal(helpers.finalizeOperationOutcome(state).outcome,expected);assert.deepEqual(state,before);}});
test('owned or nonterminal busy and cutoff failures remain red; manual overdue and writer deadline remain red',()=>{for(const state of [{stage:'done',errorCategory:'writer_busy',lockSha:'owned'},{stage:'findDaily',errorCategory:'writer_busy'},{stage:'done',runKind:'scheduled',errorCategory:'operation_overdue',lockSha:'owned'},{stage:'calendar',runKind:'scheduled',errorCategory:'operation_overdue'},{stage:'done',runKind:'manual',errorCategory:'operation_overdue'},{stage:'done',runKind:'scheduled',errorCategory:'writer_deadline'}]){assert.equal(helpers.operationOutcome(state).outcome,'failed');assert.throws(()=>helpers.finalizeOperationOutcome(state),/Stockscreener operation failed:/);}});
